### ISSUE TITLE
cgroup settings and ssh

### ISSUE THREAD

**Issue by chadbrewbaker** [bottlerocket-os/bottlerocket-control-container#13]
**Image I'm using:**

**Issue or Feature Request:**
This is how Facebook has their cgroup limits set for production https://youtu.be/cSJFLBJusVY?t=2222

How should they be set for this container? How should the build be modified to add one for ssh users?

**Comment by jhaynes** [comment]
Hi @chadbrewbaker 

Can you expand on your question a little bit? Today, we don't apply any restrictions on host containers because we expect them to be mostly idle. Have you run into issues with host containers consuming too many resources? 

Some more context: we expect Bottlerocket customers to be connecting directly to running instances rarely and almost exclusively for debugging or exploration. As such, we chose to leave host containers un-restricted to allow more flexibility during these rare connections.

**Comment by zmrow** [comment]
Hi @chadbrewbaker - we haven't heard back from you in awhile so we'll go ahead and close this.  Please feel free to re-open if you have more to add. :)
