### ISSUE TITLE
Non-AWS control container

### ISSUE THREAD

**Issue by taqtiqa-mark** [bottlerocket-os/bottlerocket-control-container#35]
**Image I'm using:**

**Issue or Feature Request:**
Is it possible to have a control container that is independent of AWS?
Is there any documentation on how to achieve this? That is, the functionality and integration points the container provides/respects.

I assume such a container would be associated with a new variant?

**Comment by jpculp** [comment]
Thanks for reaching out @taqtiqa-mark! Can you elaborate on the use-case a bit? The control container is reliant on AWS Systems Manager session console for access. If you are using Bottlerocket on-prem and want to connect to to Systems Manager via hybrid-activations I would follow the guide [here](https://github.com/bottlerocket-os/bottlerocket-control-container#connecting-to-aws-systems-manager-ssm). Otherwise, I think you probably want to use the admin container (perhaps with `superpowered = false`). Both containers have access to the `apiclient`.

**Comment by taqtiqa-mark** [comment]
> Can you elaborate on the use-case a bit?

To have a control container that is independent of AWS, that is same functionality, console access, etc.
Starting with Teleport seems reasonable - there may be others?

> you probably want to use the admin container

Doesn't that weaken the security model?

**Comment by jpculp** [comment]
By default the admin container has `superpowered = true` which would weaken the security model. To reduce the privileges you would want to set `superpowered = false` via user data.

Of course, you can always create your own custom control container and set a custom source in user data (without needing to build a special variant) like so:
```toml
[settings.host-containers.control]
source = "some-registry/my-custom-control-container:v0.1.0"
```

Things like `apiclient`, `/etc/bottlerocket-release`, and `/var/lib/bottlerocket/inventory/application.json` are mounted up automatically, but I would use the current control container's Dockerfile as a reference for things like adding the expected api group or the admin container helper scripts.

**Comment by stmcginnis** [comment]
This question appears to have been answered by @jpculp's comment, so going to close this issue. If that is not the case, please feel free to reopen this issue or file a new one with any additional questions. Thanks!
